name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs: 
  test:
    name: Maven Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test in Maven
      run: mvn test
      
  build_and_push:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: nathanjukes/rater-rate-control:latest

  deploy_to_digital_ocean:
    name: Deploy to Digital Ocean Droplet
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ./apps/rater-rate-control-service
            docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password-stdin <<<'${{ secrets.DOCKERHUB_PASSWORD }}'
            docker stop rater-rate-control-service
            docker rm rater-rate-control-service
            docker pull nathanjukes/rater-rate-control:latest
            docker run -p 8080:8080 -e DB_URL=${{ secrets.DB_URL }} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e RATER_MANAGEMENT_HOST=${{ secrets.RATER_MANAGEMENT_HOST }} -e RATER_MANAGEMENT_PORT=${{ secrets.RATER_MANAGEMENT_PORT }} -e REDIS_HOST=my-redis -e REDIS_PORT=${{ secrets.REDIS_PORT }} -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e spring.profiles.active=prod -d --name rater-rate-control-service --network=my-network nathanjukes/rater-rate-control:latest